# Laboratory Task 5

1. Perform Standard Imports

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import sys

2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.

In [14]:
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

3. Create a NumPy array called “arr” that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.

In [15]:
set_seed(42)
arr = np.random.randint(0, 5, 6)

4. Create a tensor “x” from the array above

In [4]:
x = torch.tensor(arr)
x

tensor([2, 4, 1, 2, 0, 1])

5. Change the dtype of x from int32 to int64

In [5]:
x = x.type(torch.int64)
x.dtype

torch.int64

6. Reshape x into a 3x2 tensor

In [6]:
x = x.reshape(3, 2)
x

tensor([[2, 4],
        [1, 2],
        [0, 1]])

7. Return the right-hand column of tensor x

In [16]:
rhc = x[:, 1:]
rhc

tensor([[4],
        [2],
        [1]])

8. Without changing x, return a tensor of square values of x

In [8]:
x_squared = x ** 2
x_squared

tensor([[ 4, 16],
        [ 1,  4],
        [ 0,  1]])

9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x

In [9]:
y = torch.randint(0, 5, (2, 3))
y

tensor([[2, 2, 1],
        [4, 1, 0]])

10. Find the matrix product of x and y.

In [12]:
matrix_product = torch.matmul(x, y)
print(matrix_product)

tensor([[20,  8,  2],
        [10,  4,  1],
        [ 4,  1,  0]])
